version: "3"

services:
  article_parser_go:
    build:
      context: .
      dockerfile: Dockerfile
    image: article-parser-go
    container_name: article-parser-go
    ports:
      - 7251:7251
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    environment:
      - HOST=
      - PORT=
    networks:
      - micro-net
    restart: always
    command: >
      /go/bin/app

networks:
  micro-net:
    external: true
