version: "3"

services:
  api_gateway_deno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-deno
    ports:
      - 7150:7150
    working_dir: /app
    networks:
      - micro-net
    restart: always
    command: >
      trex run start

networks:
  micro-net:
    external: true
